title: SmartPicks Daily Deals
description: Fresh Amazon UK deals posted automatically every day.
theme: minima

# You are a *project* site under the user 'Isejes'
url: "https://isejes.github.io"
baseurl: "/smartpicksdaily.github.io"

permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
