title: SmartPicks Daily Deals
description: Fresh Amazon UK deals posted automatically every day.
theme: minima

url: "https://isejes.github.io"
baseurl: "/smartpicksdaily.github.io"

# Simpler, standard permalink
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

header_pages: []
